# --- Listener MQTT clásico (TCP) --- sin TLS
# Escucha en el puerto 1883 y en todas las interfaces del contenedor.
# La dirección se indica en listener; bind_address ya no es necesario.
listener 1883 0.0.0.0
protocol mqtt

# Permite conexiones anónimas (sin usuario/contraseña).
# IMPORTANTE: solo para entorno de desarrollo local.
# allow_anonymous true

allow_anonymous false
password_file /mosquitto/config/password_file
acl_file /mosquitto/config/acl_file

# --- Persistencia de mensajes ---
# persistence permite que Mosquitto guarde los mensajes y el estado de las suscripciones en disco, 
# para que puedan recuperarse después de un reinicio.
persistence true
# Directorio donde se almacenarán los datos persistentes (mensajes y estado de suscripciones).
persistence_location /mosquitto/data/

# --- Logs ---
# Destino de los logs: archivo y salida estándar (stdout).
log_dest file /mosquitto/log/mosquitto.log
# stdout es útil para ver los logs directamente en la consola del contenedor.
log_dest stdout
# log_type puede ser: error, warning, notice, information, debug, en este caso se registrarán todos los tipos de logs.
log_type all